package naya.ganj.app.utility

object Constant {
    const val pageIndex = "pageIndex"
    const val PRODUCT_ID = "productId"
    const val ACTION = "action"
    const val VARIANT_ID = "variantId"
    const val QUANTITY = "quantity"
    const val PRODUCT = "products"
    const val PROMO_CODE = "promoCodeId"
    const val CATEGORY_ID = "categoryId"
    const val TEXT = "text"
    const val ORDER_ID = "orderId"
    const val DEVICE_TYPE = "Android"

    const val firstName = "firstName"
    const val LastName = "lastName"
    const val contactNumber = "contactNumber"
    const val houseNo = "houseNo"
    const val ApartName = "ApartName"
    const val street = "street"
    const val landmark = "landmark"
    const val city = "city"
    const val pincode = "pincode"
    const val nickName = "nickName"
    const val lat = "lat"
    const val long = "long"
    const val addressId = "addressId"
    const val mode = "mode"
    const val promoCodeId = "promoCodeId"
    const val cashBackAmount = "cashBackAmount"
    const val orderId = "orderId"
    const val orderStatus = "orderStatus"
    const val totalItems = "totalItems"
    const val MobileNumber = "mobileNumber"
    const val deviceId = "deviceId"
    const val deviceToken = "deviceToken"
    const val OTP = "otp"
    const val newname = "newName"
    const val newemailid = "newEmailId"
    const val USER_DETAILS = "user_detail"
    const val LOGIN_SESSION = "login_session"
    const val PREFS_NAME = "NAYAGANJ"
    const val LANGUAGE = "language"
    const val isListActivity = "islistactivity"
    const val categoryId = "categoryId"
    const val text="text"

    const val INSERT = "insert"
    const val ADD = "add"
    const val REMOVE = "remove"


}